name: API Call with Secret

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call external API using secret
        run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_API_KEY }}" https://api.example.com/data
